spring.application.name=versioned
spring.datasource.url=jdbc:postgresql://192.168.0.102:2311/alic3_db
spring.datasource.username=postgres
spring.datasource.password=2311
spring.datasource.driver-class-name=org.postgresql.Driver

#HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=my-ssl-cert


# Opcionales para JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Poblar
dataloader.enabled=false

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
